name: CIFuzz
on:
  pull_request:
jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    steps:
      - name: Build Fuzzers
        id: build
        uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@6601b45b1f929eb716469f6e22241a180bb52970 # master
        with:
          oss-fuzz-project-name: "prometheus"
          dry-run: false
      - name: Run Fuzzers
        uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@6601b45b1f929eb716469f6e22241a180bb52970 # master
        with:
          oss-fuzz-project-name: "prometheus"
          fuzz-seconds: 600
          dry-run: false
      - name: Upload Crash
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        if: failure() && steps.build.outcome == 'success'
        with:
          name: artifacts
          path: ./out/artifacts
